export type SourceCatalogEntry = {
  key: string;
  name: string;
  category: 'ats-api' | 'ats-feed' | 'hosted-career-site' | 'aggregator';
  integrationMethod: string;
  access: 'public' | 'partner' | 'customer-auth' | 'high-risk';
  recommended: boolean;
  status: 'ready' | 'next' | 'conditional' | 'avoid';
  docsUrl: string;
  notes: string;
};

export const SOURCE_CATALOG: SourceCatalogEntry[] = [
  {
    key: 'greenhouse',
    name: 'Greenhouse Job Board API',
    category: 'ats-api',
    integrationMethod: 'Public JSON endpoints per board token',
    access: 'public',
    recommended: true,
    status: 'ready',
    docsUrl: 'https://developer.greenhouse.io/job-board.html',
    notes: 'Best first-class connector. Public GET access for published jobs, with stable JSON and predictable board tokens.',
  },
  {
    key: 'lever',
    name: 'Lever Postings API',
    category: 'ats-api',
    integrationMethod: 'Public postings JSON per site slug',
    access: 'public',
    recommended: true,
    status: 'ready',
    docsUrl: 'https://github.com/lever/postings-api',
    notes: 'High-value connector for startup and growth-company roles. Public postings are accessible without employer credentials.',
  },
  {
    key: 'ashby',
    name: 'Ashby Job Postings API',
    category: 'ats-api',
    integrationMethod: 'Public job-board endpoint per Ashby board',
    access: 'public',
    recommended: true,
    status: 'next',
    docsUrl: 'https://developers.ashbyhq.com/docs/public-job-posting-api',
    notes: 'Strong candidate for the next connector. Modern API and clean published job payloads.',
  },
  {
    key: 'smartrecruiters',
    name: 'SmartRecruiters Posting API',
    category: 'ats-api',
    integrationMethod: 'Posting API backed by customer API key',
    access: 'customer-auth',
    recommended: true,
    status: 'conditional',
    docsUrl: 'https://developers.smartrecruiters.com/docs/posting-api',
    notes: 'Good enterprise target, but employer access is needed. Not universal public scraping.',
  },
  {
    key: 'workable',
    name: 'Workable Jobs API',
    category: 'ats-api',
    integrationMethod: 'SPI jobs endpoints using employer token',
    access: 'customer-auth',
    recommended: true,
    status: 'conditional',
    docsUrl: 'https://help.workable.com/hc/en-us/articles/115012771647-Using-the-Workable-API-to-create-a-careers-page',
    notes: 'Usable when a customer or partner provides access. Better for direct integrations than broad scraping.',
  },
  {
    key: 'teamtailor',
    name: 'Teamtailor API / XML feeds',
    category: 'ats-feed',
    integrationMethod: 'Public-read API key or job-board XML/webhook integrations',
    access: 'partner',
    recommended: true,
    status: 'conditional',
    docsUrl: 'https://partner.teamtailor.com/job_boards/',
    notes: 'Excellent long-term connector, but access model is partner or customer driven rather than anonymous public scraping.',
  },
  {
    key: 'recruitee',
    name: 'Recruitee Careers Site API / Widget',
    category: 'ats-api',
    integrationMethod: 'Careers Site API or hosted widget',
    access: 'customer-auth',
    recommended: true,
    status: 'conditional',
    docsUrl: 'https://support.recruitee.com/articles/1066282-api-documentation/',
    notes: 'Useful if a customer exposes their careers site through Recruitee APIs or widgets.',
  },
  {
    key: 'personio',
    name: 'Personio Recruiting API / XML',
    category: 'ats-feed',
    integrationMethod: 'Recruiting API and XML career-page integration',
    access: 'customer-auth',
    recommended: true,
    status: 'conditional',
    docsUrl: 'https://support.personio.de/hc/en-us/articles/360000314338-The-Personio-Recruiting-API',
    notes: 'Good for employer-managed integrations. XML option is especially practical when available.',
  },
  {
    key: 'icims',
    name: 'iCIMS Job Portal API / Standard XML Feed',
    category: 'ats-feed',
    integrationMethod: 'Portal API or authenticated XML feed for approved vendors',
    access: 'partner',
    recommended: true,
    status: 'conditional',
    docsUrl: 'https://developer-community.icims.com/platform/services/standard-xml-feed-job-boards',
    notes: 'Strong source once onboarded as a vendor. Good enterprise coverage, but not anonymous access.',
  },
  {
    key: 'taleo',
    name: 'Oracle Taleo Career Sections',
    category: 'hosted-career-site',
    integrationMethod: 'Public career-section pages and jobdetail URLs',
    access: 'public',
    recommended: true,
    status: 'next',
    docsUrl: 'https://docs.oracle.com/en/cloud/saas/taleo-enterprise/20d/otcug/career-sections.html',
    notes: 'Typically collected from public career-section pages rather than a single modern public API. High enterprise coverage.',
  },
  {
    key: 'jobvite',
    name: 'Jobvite Hosted Career Sites',
    category: 'hosted-career-site',
    integrationMethod: 'Hosted career site pages and widgets',
    access: 'public',
    recommended: true,
    status: 'next',
    docsUrl: 'https://careers.jobvite.com/careersite/integration.html',
    notes: 'Often reachable through public hosted sites. Better treated as a career-site parser than a unified API connector.',
  },
  {
    key: 'linkedin',
    name: 'LinkedIn Jobs',
    category: 'aggregator',
    integrationMethod: 'No scraping; only approved platform integrations',
    access: 'high-risk',
    recommended: false,
    status: 'avoid',
    docsUrl: 'https://www.linkedin.com/legal/user-agreement',
    notes: 'LinkedIn explicitly prohibits crawlers, bots, and scraping of its services.',
  },
  {
    key: 'indeed',
    name: 'Indeed',
    category: 'aggregator',
    integrationMethod: 'No scraping unless explicitly authorized',
    access: 'high-risk',
    recommended: false,
    status: 'avoid',
    docsUrl: 'https://www.indeed.com/legal?hl=en_US',
    notes: 'Indeed terms keep scraping, bots, and automated activity prohibited unless permission is granted.',
  },
  {
    key: 'glassdoor',
    name: 'Glassdoor',
    category: 'aggregator',
    integrationMethod: 'No scraping without express written permission',
    access: 'high-risk',
    recommended: false,
    status: 'avoid',
    docsUrl: 'https://www.glassdoor.com/about/terms/',
    notes: 'Glassdoor terms prohibit robots, spiders, scrapers, and automated extraction without permission.',
  },
];
